### ISSUE TITLE
Typography and Colors (Tailwind)

### ISSUE THREAD

**Issue by kblake1121** [singlestone/sugar#214]

**Comment by pcmart03** [comment]
I think this might be done. We've settled on default colors and font, and I've documented how to change them.

The only thing we probably need to discuss is our take on heading styles. I don't want to declare an h1 style, but do we need a t-shirt size scale with opinions on line height and letter spacing? 

Also, because blog style content isn't in scope for Sugar, should just recommend the official Tailwind typography plugin for those use cases?
